# Generated by Django 5.0.6 on 2024-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='service image')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
